# Generated by Django 5.2.8 on 2026-03-04 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('db', '0002_alter_peerinfo_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── Model renames ──────────────────────────────────────────────
        migrations.RenameModel(
            old_name='AutidConnLog',
            new_name='AuditConnLog',
        ),
        migrations.RenameModel(
            old_name='UserPrefile',
            new_name='UserProfile',
        ),

        # ── Meta-only changes ──────────────────────────────────────────
        migrations.AlterModelOptions(
            name='clienttags',
            options={'verbose_name': '设备标签关联'},
        ),
        migrations.AlterModelOptions(
            name='loginclient',
            options={'ordering': ['-user'], 'verbose_name': '登录客户端', 'verbose_name_plural': '登录客户端'},
        ),
        migrations.AlterModelOptions(
            name='sharepersonal',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name': '分享地址簿记录',
                     'verbose_name_plural': '分享地址簿记录'},
        ),

        # ── FK field renames (AlterField + RenameField pairs) ──────────
        # ClientTags.user_id -> user
        migrations.AlterField(
            model_name='clienttags',
            name='user_id',
            field=models.ForeignKey(db_column='user_id_id', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='user_tags', to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.RenameField(
            model_name='clienttags',
            old_name='user_id',
            new_name='user',
        ),
        # LoginClient.user_id -> user
        migrations.AlterField(
            model_name='loginclient',
            name='user_id',
            field=models.ForeignKey(db_column='user_id_id', on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.RenameField(
            model_name='loginclient',
            old_name='user_id',
            new_name='user',
        ),
        # Personal.create_user_id -> creator
        migrations.AlterField(
            model_name='personal',
            name='create_user_id',
            field=models.ForeignKey(db_column='create_user_id_id', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='personal_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='create_user_id',
            new_name='creator',
        ),
        # Token.user_id -> user
        migrations.AlterField(
            model_name='token',
            name='user_id',
            field=models.ForeignKey(db_column='user_id_id', on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.RenameField(
            model_name='token',
            old_name='user_id',
            new_name='user',
        ),

        # ── unique_together updates for renamed fields ─────────────────
        migrations.AlterUniqueTogether(
            name='personal',
            unique_together={('personal_name', 'creator')},
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set(),
        ),

        # ── Remove / add fields ───────────────────────────────────────
        migrations.RemoveField(
            model_name='heartbeat',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='log',
            name='user_id',
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(db_column='user_id_id', default=None, null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='peerinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='personal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='token',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),

        # ── UserConfig: OneToOneField(user_id) -> ForeignKey(user) ─────
        # Step 1: drop old unique_together referencing old field name
        migrations.AlterUniqueTogether(
            name='userconfig',
            unique_together=set(),
        ),
        # Step 2: alter field type in-place (OneToOne -> FK, same db column)
        migrations.AlterField(
            model_name='userconfig',
            name='user_id',
            field=models.ForeignKey(
                db_column='user_id_id',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_configs',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        # Step 3: rename Python field name
        migrations.RenameField(
            model_name='userconfig',
            old_name='user_id',
            new_name='user',
        ),
        # Step 4: set new unique_together with new field name
        migrations.AlterUniqueTogether(
            name='userconfig',
            unique_together={('user', 'config_name')},
        ),

        # ── AlterField: FK conversions, choices, indexes ───────────────
        migrations.AlterField(
            model_name='clienttags',
            name='guid',
            field=models.ForeignKey(db_column='guid', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='client_tags', to='db.personal', to_field='guid'),
        ),
        migrations.AlterField(
            model_name='clienttags',
            name='peer_id',
            field=models.CharField(db_index=True, max_length=255, verbose_name='设备ID'),
        ),
        migrations.AlterField(
            model_name='clienttags',
            name='tags',
            field=models.JSONField(default=list, verbose_name='标签ID列表'),
        ),
        migrations.AlterField(
            model_name='loginclient',
            name='client_type',
            field=models.CharField(choices=[('web', 'web'), ('client', 'client')], default='client', max_length=255,
                                   verbose_name='客户端类型'),
        ),
        migrations.AlterField(
            model_name='loginclient',
            name='platform',
            field=models.CharField(
                choices=[('windows', 'Windows'), ('macos', 'MacOS'), ('linux', 'Linux'), ('android', 'Android'),
                         ('ios', 'iOS'), ('web', 'Web')], max_length=255, null=True, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='loginclient',
            name='uuid',
            field=models.CharField(db_index=True, max_length=255, verbose_name='设备UUID'),
        ),
        migrations.AlterField(
            model_name='peerinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='peerinfo',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='guid',
            field=models.ForeignKey(db_column='guid', on_delete=django.db.models.deletion.CASCADE, related_name='tags',
                                    to='db.personal', to_field='guid'),
        ),
        migrations.AlterField(
            model_name='token',
            name='client_type',
            field=models.CharField(choices=[('web', 'web'), ('client', 'client'), ('api', 'api')], default='client',
                                   max_length=255, verbose_name='客户端类型'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(db_index=True, max_length=255, verbose_name='令牌'),
        ),
        migrations.AlterField(
            model_name='token',
            name='uuid',
            field=models.CharField(db_index=True, max_length=255, verbose_name='设备UUID'),
        ),

        # ── Remaining unique_together fixes ────────────────────────────
        migrations.AlterUniqueTogether(
            name='alias',
            unique_together={('peer_id', 'guid')},
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('user', 'uuid')},
        ),

        # ── New models ─────────────────────────────────────────────────
        migrations.CreateModel(
            name='ShareToGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('from_user', models.ForeignKey(db_column='from_share_id', on_delete=django.db.models.deletion.CASCADE,
                                                related_name='sent_group_shares', to=settings.AUTH_USER_MODEL)),
                ('personal', models.ForeignKey(db_column='guid', on_delete=django.db.models.deletion.CASCADE,
                                               related_name='shared_to_groups', to='db.personal', to_field='guid')),
                ('to_group', models.ForeignKey(db_column='to_share_id', on_delete=django.db.models.deletion.CASCADE,
                                               related_name='received_group_shares', to='auth.group')),
            ],
            options={
                'verbose_name': '分享地址簿给用户组',
                'verbose_name_plural': '分享地址簿给用户组',
                'db_table': 'share_to_group',
                'ordering': ['-created_at'],
                'unique_together': {('personal', 'to_group')},
            },
        ),
        migrations.CreateModel(
            name='ShareToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('from_user', models.ForeignKey(db_column='from_share_id', on_delete=django.db.models.deletion.CASCADE,
                                                related_name='sent_shares', to=settings.AUTH_USER_MODEL)),
                ('personal', models.ForeignKey(db_column='guid', on_delete=django.db.models.deletion.CASCADE,
                                               related_name='shared_to_users', to='db.personal', to_field='guid')),
                ('to_user', models.ForeignKey(db_column='to_share_id', on_delete=django.db.models.deletion.CASCADE,
                                              related_name='received_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '分享地址簿给用户',
                'verbose_name_plural': '分享地址簿给用户',
                'db_table': 'share_to_user',
                'ordering': ['-created_at'],
                'unique_together': {('personal', 'to_user')},
            },
        ),
    ]
