# Generated by Django 6.0.2 on 2026-03-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0003_rename_autidconnlog_auditconnlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="peerinfo",
            name="is_enabled",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AddField(
            model_name="peerinfo",
            name="note",
            field=models.TextField(blank=True, default="", verbose_name="备注"),
        ),
    ]
