# Generated by Django 6.0.2 on 2026-03-04 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0004_peerinfo_is_enabled_peerinfo_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="设备组名称"
                    ),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="备注")),
            ],
            options={
                "verbose_name": "设备组",
                "verbose_name_plural": "设备组",
                "db_table": "device_group",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="peerinfo",
            name="device_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="peers",
                to="db.devicegroup",
                verbose_name="所属设备组",
            ),
        ),
    ]
