# Generated by Django 6.0.2 on 2026-03-06 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("db", "0005_devicegroup_peerinfo_device_group"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="角色名称"
                    ),
                ),
                ("note", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认角色"),
                ),
            ],
            options={
                "verbose_name": "角色",
                "verbose_name_plural": "角色",
                "db_table": "role",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeviceGroupPeer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_peers",
                        to="db.devicegroup",
                        verbose_name="设备组",
                    ),
                ),
                (
                    "peer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_groups",
                        to="db.peerinfo",
                        verbose_name="设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "设备组设备关联",
                "verbose_name_plural": "设备组设备关联",
                "db_table": "device_group_peer",
                "unique_together": {("device_group", "peer")},
            },
        ),
        migrations.CreateModel(
            name="GroupDeviceGroupPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("permission", models.IntegerField(default=0, verbose_name="权限位")),
                (
                    "device_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_permissions",
                        to="db.devicegroup",
                        verbose_name="设备组",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_group_permissions",
                        to="auth.group",
                        verbose_name="用户组",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户组设备组权限",
                "verbose_name_plural": "用户组设备组权限",
                "db_table": "group_device_group_permission",
                "unique_together": {("group", "device_group")},
            },
        ),
        migrations.CreateModel(
            name="GroupDevicePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("permission", models.IntegerField(default=0, verbose_name="权限位")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_permissions",
                        to="auth.group",
                        verbose_name="用户组",
                    ),
                ),
                (
                    "peer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_permissions",
                        to="db.peerinfo",
                        verbose_name="设备",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户组设备权限",
                "verbose_name_plural": "用户组设备权限",
                "db_table": "group_device_permission",
                "unique_together": {("group", "peer")},
            },
        ),
        migrations.CreateModel(
            name="RoleDeviceGroupPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("permission", models.IntegerField(default=0, verbose_name="权限位")),
                (
                    "device_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="db.devicegroup",
                        verbose_name="设备组",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_group_permissions",
                        to="db.role",
                        verbose_name="角色",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色设备组权限",
                "verbose_name_plural": "角色设备组权限",
                "db_table": "role_device_group_permission",
                "unique_together": {("role", "device_group")},
            },
        ),
        migrations.CreateModel(
            name="RoleDevicePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("permission", models.IntegerField(default=0, verbose_name="权限位")),
                (
                    "peer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions",
                        to="db.peerinfo",
                        verbose_name="设备",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_permissions",
                        to="db.role",
                        verbose_name="角色",
                    ),
                ),
            ],
            options={
                "verbose_name": "角色设备权限",
                "verbose_name_plural": "角色设备权限",
                "db_table": "role_device_permission",
                "unique_together": {("role", "peer")},
            },
        ),
        migrations.CreateModel(
            name="UserDeviceGroupPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("permission", models.IntegerField(default=0, verbose_name="权限位")),
                (
                    "device_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_permissions",
                        to="db.devicegroup",
                        verbose_name="设备组",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_group_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户设备组权限",
                "verbose_name_plural": "用户设备组权限",
                "db_table": "user_device_group_permission",
                "unique_together": {("user", "device_group")},
            },
        ),
        migrations.CreateModel(
            name="UserDevicePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("permission", models.IntegerField(default=0, verbose_name="权限位")),
                (
                    "peer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_permissions",
                        to="db.peerinfo",
                        verbose_name="设备",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_permissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户设备权限",
                "verbose_name_plural": "用户设备权限",
                "db_table": "user_device_permission",
                "unique_together": {("user", "peer")},
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_users",
                        to="db.role",
                        verbose_name="角色",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户角色关联",
                "verbose_name_plural": "用户角色关联",
                "db_table": "user_role",
                "unique_together": {("user", "role")},
            },
        ),
    ]
