# Generated by Django 6.0.2 on 2026-03-06 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("db", "0007_seed_permission_data"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="groupdevicepermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="groupdevicepermission",
            name="group",
        ),
        migrations.RemoveField(
            model_name="groupdevicepermission",
            name="peer",
        ),
        migrations.AlterUniqueTogether(
            name="roledevicegrouppermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="roledevicegrouppermission",
            name="device_group",
        ),
        migrations.RemoveField(
            model_name="roledevicegrouppermission",
            name="role",
        ),
        migrations.AlterUniqueTogether(
            name="roledevicepermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="roledevicepermission",
            name="peer",
        ),
        migrations.RemoveField(
            model_name="roledevicepermission",
            name="role",
        ),
        migrations.AlterUniqueTogether(
            name="userdevicegrouppermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userdevicegrouppermission",
            name="device_group",
        ),
        migrations.RemoveField(
            model_name="userdevicegrouppermission",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="userdevicepermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userdevicepermission",
            name="peer",
        ),
        migrations.RemoveField(
            model_name="userdevicepermission",
            name="user",
        ),
        migrations.AddField(
            model_name="role",
            name="permission",
            field=models.IntegerField(default=0, verbose_name="全局权限位"),
        ),
        migrations.CreateModel(
            name="GroupRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_roles",
                        to="auth.group",
                        verbose_name="用户组",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_groups",
                        to="db.role",
                        verbose_name="角色",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户组角色关联",
                "verbose_name_plural": "用户组角色关联",
                "db_table": "group_role",
                "unique_together": {("group", "role")},
            },
        ),
        migrations.DeleteModel(
            name="GroupDeviceGroupPermission",
        ),
        migrations.DeleteModel(
            name="GroupDevicePermission",
        ),
        migrations.DeleteModel(
            name="RoleDeviceGroupPermission",
        ),
        migrations.DeleteModel(
            name="RoleDevicePermission",
        ),
        migrations.DeleteModel(
            name="UserDeviceGroupPermission",
        ),
        migrations.DeleteModel(
            name="UserDevicePermission",
        ),
    ]
