# Generated by Django 6.0.2 on 2026-04-20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0008_refactor_global_role_permission"),
    ]

    def update_default_role_permission(apps, schema_editor):
        """
        更新默认角色的权限为完整权限
        
        :param apps: Django 应用注册表
        :param schema_editor: 数据库模式编辑器
        """
        Role = apps.get_model("db", "Role")
        Role.objects.filter(name="default").update(permission=15)

    def reverse_default_role_permission(apps, schema_editor):
        """
        回滚默认角色的权限为 0
        
        :param apps: Django 应用注册表
        :param schema_editor: 数据库模式编辑器
        """
        Role = apps.get_model("db", "Role")
        Role.objects.filter(name="default").update(permission=0)

    operations = [
        migrations.RunPython(
            update_default_role_permission,
            reverse_default_role_permission,
        ),
    ]
